name: Build Dekan Installer

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Rust
        run: rustup toolchain install

      - name: Install Inno Setup
        shell: pwsh
        run: |
          $iscc = Join-Path ${env:ProgramFiles(x86)} 'Inno Setup 6\ISCC.exe'
          if (-not (Test-Path $iscc)) {
            choco install innosetup --no-progress -y
          }

      - name: Build Dekan Installer
        run: cargo run --package xtask -- installer

      - name: Upload Installer
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Dekan-Installer
          path: dist/installer/*.exe
          if-no-files-found: error
